include:
  - project: devops-public/ci-projects
    ref: master
    file: ci.yml

variables:
  CARGO_DIR: cli

stages:
  - security
  - check

audit:
  stage: security
  image: office-registry-vpc.cn-hongkong.cr.aliyuncs.com/okbase/node-rust:22.12.0-rust1.87.0-okg1.2-sec20250728
  tags:
    - Global-shared-17
  script:
    - cd $CARGO_DIR
    - cargo audit
