# Homebrew formula
# Usage:
#   brew tap okx/onchainos-skills https://github.com/okx/onchainos-skills
#   brew install onchainos
#
# This file is auto-generated by scripts/update-formula.sh. Do not edit sha256 values manually.
# Release artifacts are raw binaries (not tar.gz); Homebrew downloads and installs them directly.

class Onchainos < Formula
  desc "onchainOS CLI — token search, market data, wallet, swap, and gateway across 20+ chains"
  homepage "https://github.com/okx/onchainos-skills"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/okx/onchainos-skills/releases/download/v0.1.0/onchainos-x86_64-apple-darwin"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/okx/onchainos-skills/releases/download/v0.1.0/onchainos-aarch64-apple-darwin"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/okx/onchainos-skills/releases/download/v0.1.0/onchainos-x86_64-unknown-linux-gnu"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/okx/onchainos-skills/releases/download/v0.1.0/onchainos-aarch64-unknown-linux-gnu"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    # Downloaded artifact is a raw binary named after the URL (e.g. onchainos-aarch64-apple-darwin)
    # Glob-match it and rename to onchainos for installation into bin/
    downloaded = Dir["onchainos*"].first || "onchainos"
    bin.install downloaded => "onchainos"
  end

  test do
    assert_match "onchainos", shell_output("#{bin}/onchainos --help")
  end
end
