#!/usr/bin/env bash

set -euo pipefail

script_source="${BASH_SOURCE[0]}"
while [[ -L "$script_source" ]]; do
  script_source_dir="$(cd -P -- "$(dirname -- "$script_source")" && pwd)"
  script_source="$(readlink -- "$script_source")"
  [[ "$script_source" = /* ]] || script_source="$script_source_dir/$script_source"
done
script_dir="$(cd -P -- "$(dirname -- "$script_source")" && pwd)"
# shellcheck source=common.sh
source "$script_dir/common.sh"
load_dev_config

real_codex="$dev_repo_root/.codex/bin/codex.real"
[[ -x "$real_codex" ]] || {
  echo "error: global Codex CLI is unavailable; run npm run dev:init" >&2
  exit 1
}

# Daemon-managed Codex sessions run from the isolated A2A workspace and do not
# discover the checkout's .codex/config.toml. Supply the project Skill entries
# explicitly and retain the stale-global disables generated by dev:skills.
skills_config="$(node "$script_dir/codex-skill-config.mjs" "$dev_repo_root")"

exec "$real_codex" -c "skills.config=$skills_config" "$@"
